"""Initial Database: Users, Codes, and Notifications

Revision ID: 4b16e304bcb8
Revises: 
Create Date: 2023-10-23 11:55:52.438877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b16e304bcb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.String(length=37), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('stamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('stamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.String(length=32), nullable=True),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zipcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_table('codes')
    # ### end Alembic commands ###
